[package]
authors.workspace = true
description = "A library with the core functionality needed to implement a BitTorrent HTTP tracker."
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["api", "bittorrent", "core", "library", "tracker"]
license.workspace = true
name = "bittorrent-http-tracker-core"
publish.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aquatic_udp_protocol = "0"
bittorrent-http-protocol = { version = "3.0.0-develop", path = "../http-protocol" }
bittorrent-primitives = "0.1.0"
bittorrent-tracker-core = { version = "3.0.0-develop", path = "../tracker-core" }
futures = "0"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
torrust-tracker-configuration = { version = "3.0.0-develop", path = "../configuration" }
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
tracing = "0"

[dev-dependencies]
mockall = "0"
torrust-tracker-test-helpers = { version = "3.0.0-develop", path = "../test-helpers" }
