[package]
description = "A library with the primitive types and functions for the BitTorrent UDP tracker protocol."
keywords = ["bittorrent", "library", "primitives", "udp"]
name = "bittorrent-udp-tracker-protocol"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aquatic_udp_protocol = "0"
torrust-tracker-clock = { version = "3.0.0-develop", path = "../clock" }
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
