name: Deployment

on:
  push:
    branches:
      - "releases/**/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [nightly, stable]

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: setup
        name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - id: test
        name: Run Unit Tests
        run: cargo test --tests --benches --examples --workspace --all-targets --all-features

  publish:
    name: Publish
    environment: deployment
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable]

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: setup
        name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - id: publish
        name: Publish Crates
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.TORRUST_UPDATE_CARGO_REGISTRY_TOKEN }}"
        run: |
          cargo publish -p bittorrent-http-tracker-core
          cargo publish -p bittorrent-http-tracker-protocol
          cargo publish -p bittorrent-tracker-client
          cargo publish -p bittorrent-tracker-core
          cargo publish -p bittorrent-udp-tracker-core
          cargo publish -p bittorrent-udp-tracker-protocol
          cargo publish -p torrust-axum-http-tracker-server
          cargo publish -p torrust-axum-server
          cargo publish -p torrust-torrust-server-lib
          cargo publish -p torrust-tracker
          cargo publish -p torrust-tracker-api-client
          cargo publish -p torrust-tracker-api-core
          cargo publish -p torrust-tracker-client
          cargo publish -p torrust-tracker-clock
          cargo publish -p torrust-tracker-configuration
          cargo publish -p torrust-tracker-contrib-bencode
          cargo publish -p torrust-tracker-located-error
          cargo publish -p torrust-tracker-primitives
          cargo publish -p torrust-tracker-test-helpers
          cargo publish -p torrust-tracker-torrent-repository

          
